# ============================================================
# TASK 2 - PANDAS ETL
# ============================================================
#
# Objective:
#
# Use Pandas to process the large CSV generated in Task 1.
#
# ETL means:
#
#   E = Extract
#   T = Transform
#   L = Load
#
# In this first step we are focusing on:
#
#   EXTRACT + INSPECT
#
# We will NOT modify the data yet.
#
# ============================================================


import os
import time
import pandas as pd


# ============================================================
# CONFIGURATION
# ============================================================

# Path of our generated CSV file.
#
# Current project structure:
#
# day_01_python_basics/
# └── day_02_local_etl/
#     ├── data_generation/
#     │   └── output/
#     │       └── large_dataset.csv
#     │
#     └── pandas_etl/
#         └── pandas_etl.py
#
# Therefore we go:
#
# pandas_etl
#     ↓
# ..
#     ↓
# data_generation
#     ↓
# output
#     ↓
# large_dataset.csv


# Get the directory where pandas_etl.py is located.
SCRIPT_DIR = os.path.dirname(
    os.path.abspath(__file__)
)


# Go from:
#
# pandas_etl/
#
# to:
#
# day_02_local_etl/
#
DAY_02_DIR = os.path.dirname(
    SCRIPT_DIR
)


# Build the complete path to the generated CSV.
INPUT_FILE = os.path.join(
    DAY_02_DIR,
    "data_generation",
    "output",
    "large_dataset.csv"
)

# ============================================================
# PROJECT DIRECTORIES
# ============================================================

from pathlib import Path

# Directory where this Python file is located
BASE_DIR = Path(__file__).resolve().parent

# Input CSV generated by Task 1
INPUT_FILE = (
    BASE_DIR.parent
    / "data_generation"
    / "output"
    / "large_dataset.csv"
)

# Output directory for processed files
OUTPUT_DIR = (
    BASE_DIR.parent
    / "output"
)

# ============================================================
# EXTRACT
# ============================================================

def extract_data():
    """
    Read the CSV file using Pandas.

    pd.read_csv() loads the CSV into a Pandas DataFrame.
    """

    print("=" * 70)
    print("EXTRACT - READING CSV")
    print("=" * 70)

    print(
        f"Input file: {INPUT_FILE}"
    )

    print()

    # Start measuring loading time.

    start_time = time.perf_counter()


    # --------------------------------------------------------
    # Read CSV
    # --------------------------------------------------------

    df = pd.read_csv(
        INPUT_FILE
    )


    # Calculate loading time.

    loading_time = (
        time.perf_counter()
        - start_time
    )


    print(
        f"CSV loaded successfully."
    )

    print(
        f"Loading time: "
        f"{loading_time:.4f} seconds"
    )

    print()

    return df, loading_time


# ============================================================
# INSPECT DATASET
# ============================================================

def inspect_dataset(df):
    """
    Inspect the loaded Pandas DataFrame.
    """

    print("=" * 70)
    print("DATASET INSPECTION")
    print("=" * 70)


    # ========================================================
    # 1. Number of rows and columns
    # ========================================================

    rows, columns = df.shape


    print(
        f"Rows    : {rows:,}"
    )

    print(
        f"Columns : {columns:,}"
    )

    print()


    # ========================================================
    # 2. Column names
    # ========================================================

    print("-" * 70)

    print("COLUMN NAMES")

    print("-" * 70)


    for number, column in enumerate(
        df.columns,
        start=1
    ):

        print(
            f"{number:3}. {column}"
        )


    print()


    # ========================================================
    # 3. First 5 rows
    # ========================================================

    print("-" * 70)

    print("FIRST 5 ROWS")

    print("-" * 70)


    print(
        df.head()
    )

    print()


    # ========================================================
    # 4. Last 5 rows
    # ========================================================

    print("-" * 70)

    print("LAST 5 ROWS")

    print("-" * 70)


    print(
        df.tail()
    )

    print()


    # ========================================================
    # 5. Data types
    # ========================================================

    print("-" * 70)

    print("DATA TYPES")

    print("-" * 70)


    print(
        df.dtypes
    )

    print()


    # ========================================================
    # 6. Pandas info()
    # ========================================================

    print("-" * 70)

    print("DATAFRAME INFO")

    print("-" * 70)


    df.info()

    print()


    # ========================================================
    # 7. Missing values
    # ========================================================

    print("-" * 70)

    print("MISSING VALUES")

    print("-" * 70)


    null_counts = df.isnull().sum()


    # Only show columns that actually contain nulls.

    null_columns = (
        null_counts[
            null_counts > 0
        ]
        .sort_values(
            ascending=False
        )
    )


    if len(null_columns) == 0:

        print(
            "No missing values found."
        )

    else:

        print(
            null_columns
        )


    print()


    # ========================================================
    # 8. Total missing values
    # ========================================================

    total_missing = (
        df.isnull()
        .sum()
        .sum()
    )


    print(
        f"Total missing values: "
        f"{total_missing:,}"
    )

    print()


    # ========================================================
    # 9. Duplicate records
    # ========================================================

    print("-" * 70)

    print("DUPLICATE RECORDS")

    print("-" * 70)


    duplicate_count = (
        df.duplicated()
        .sum()
    )


    print(
        f"Duplicate rows: "
        f"{duplicate_count:,}"
    )

    print()


    # ========================================================
    # 10. Basic statistics
    # ========================================================

    print("-" * 70)

    print("NUMERIC STATISTICS")

    print("-" * 70)


    print(
        df.describe()
    )

    print()

# ============================================================
# TRANSFORM - REMOVE DUPLICATES
# ============================================================

def remove_duplicates(df):
    """
    Remove completely duplicate rows.

    A duplicate means that all column values in one row
    are exactly the same as another row.

    Example:

        company_id | city     | amount
        -----------|----------|--------
        13         | Lahore   | 5000
        17         | Karachi  | 7000
        13         | Lahore   | 5000   <-- duplicate

    After drop_duplicates(), only one copy remains.
    """

    print("=" * 70)
    print("TRANSFORM - REMOVE DUPLICATES")
    print("=" * 70)

    # --------------------------------------------------------
    # Count duplicates BEFORE removing them.
    # --------------------------------------------------------

    duplicate_count = (
        df.duplicated()
        .sum()
    )

    print(
        f"Duplicate rows found: "
        f"{duplicate_count:,}"
    )


    # --------------------------------------------------------
    # Remove duplicate rows.
    #
    # We use inplace=False implicitly, meaning Pandas
    # returns a new DataFrame.
    # --------------------------------------------------------

    df_cleaned = (
        df.drop_duplicates()
    )


    # --------------------------------------------------------
    # Calculate how many rows were removed.
    # --------------------------------------------------------

    rows_removed = (
        len(df)
        - len(df_cleaned)
    )


    print(
        f"Rows removed: "
        f"{rows_removed:,}"
    )


    print(
        f"Rows before: "
        f"{len(df):,}"
    )


    print(
        f"Rows after: "
        f"{len(df_cleaned):,}"
    )


    print()


    return df_cleaned

# ============================================================
# TRANSFORM - HANDLE MISSING VALUES
# ============================================================

def handle_missing_values(df):
    """
    Handle missing/null values according to column-specific
    business rules.

    Important:
    We don't treat every missing value in the same way.

    Rules for this exercise:

        company_name -> "Unknown"
        city         -> "Unknown"
        email        -> "Unknown"

        discount     -> 0

    order_amount is intentionally left unchanged because
    a missing order amount does NOT necessarily mean zero.
    """

    print("=" * 70)
    print("TRANSFORM - HANDLE MISSING VALUES")
    print("=" * 70)

    # --------------------------------------------------------
    # Count missing values BEFORE cleaning.
    # --------------------------------------------------------

    missing_before = (
        df.isnull()
        .sum()
        .sum()
    )

    print(
        f"Total missing values before cleaning: "
        f"{missing_before:,}"
    )

    print()


    # --------------------------------------------------------
    # 1. Handle company_name
    #
    # If company_name is missing, use "Unknown".
    # --------------------------------------------------------

    if "company_name" in df.columns:

        df["company_name"] = (
            df["company_name"]
            .fillna("Unknown")
        )


    # --------------------------------------------------------
    # 2. Handle city
    #
    # If city is missing, use "Unknown".
    # --------------------------------------------------------

    if "city" in df.columns:

        df["city"] = (
            df["city"]
            .fillna("Unknown")
        )


    # --------------------------------------------------------
    # 3. Handle email
    #
    # If email is missing, use "Unknown".
    # --------------------------------------------------------

    if "email" in df.columns:

        df["email"] = (
            df["email"]
            .fillna("Unknown")
        )


    # --------------------------------------------------------
    # 4. Handle discount
    #
    # For this dataset, a missing discount means:
    #
    # "There is no discount."
    #
    # Therefore NULL becomes 0.
    # --------------------------------------------------------

    if "discount" in df.columns:

        df["discount"] = (
            df["discount"]
            .fillna(0)
        )


    # --------------------------------------------------------
    # 5. order_amount
    #
    # We intentionally DO NOT replace missing values here.
    #
    # Why?
    #
    # NULL order_amount could mean:
    #
    # - source data was incomplete
    # - order amount was not calculated
    # - data ingestion failed
    #
    # Replacing it with 0 would create fake business data.
    # --------------------------------------------------------

    print(
        "order_amount missing values were intentionally "
        "left unchanged."
    )

    print()


    # --------------------------------------------------------
    # Count missing values AFTER cleaning.
    # --------------------------------------------------------

    missing_after = (
        df.isnull()
        .sum()
        .sum()
    )

    print(
        f"Total missing values after cleaning: "
        f"{missing_after:,}"
    )

    print()


    # --------------------------------------------------------
    # Show remaining columns containing NULL values.
    # --------------------------------------------------------

    remaining_missing = (
        df.isnull()
        .sum()
    )

    remaining_missing = (
        remaining_missing[
            remaining_missing > 0
        ]
        .sort_values(
            ascending=False
        )
    )


    if len(remaining_missing) > 0:

        print(
            "Remaining missing values:"
        )

        print(
            remaining_missing
        )

    else:

        print(
            "No missing values remain."
        )

    print()


    return df

# ============================================================
# TRANSFORM - STANDARDIZE COLUMN NAMES
# ============================================================

def standardize_column_names(df):
    """
    Standardize DataFrame column names.

    Rules:

    1. Convert names to lowercase.
    2. Remove leading/trailing spaces.
    3. Replace spaces with underscores.
    4. Replace hyphens with underscores.
    5. Remove special characters.
    6. Make sure multiple underscores are collapsed.

    Example:

        "Company Name" -> "company_name"
        "Order Amount" -> "order_amount"
        "Customer-ID"  -> "customer_id"
    """

    print("=" * 70)
    print("TRANSFORM - STANDARDIZE COLUMN NAMES")
    print("=" * 70)

    print(
        f"Columns before standardization: "
        f"{len(df.columns)}"
    )

    print()

    # --------------------------------------------------------
    # Standardize every column name.
    # --------------------------------------------------------

    df.columns = (
        df.columns

        # Convert to string.
        .astype(str)

        # Remove spaces from beginning/end.
        .str.strip()

        # Convert to lowercase.
        .str.lower()

        # Replace spaces with underscores.
        .str.replace(
            " ",
            "_",
            regex=False
        )

        # Replace hyphens with underscores.
        .str.replace(
            "-",
            "_",
            regex=False
        )

        # Remove characters other than:
        # a-z, 0-9 and underscore.
        .str.replace(
            r"[^a-z0-9_]",
            "",
            regex=True
        )

        # Replace multiple underscores with one.
        .str.replace(
            r"_+",
            "_",
            regex=True
        )

        # Remove leading/trailing underscores.
        .str.strip("_")
    )

    print(
        "Column names standardized successfully."
    )

    print()

    # --------------------------------------------------------
    # Display the first 30 column names after cleaning.
    # --------------------------------------------------------

    print("First 30 standardized columns:")

    for number, column in enumerate(
        df.columns[:30],
        start=1
    ):

        print(
            f"{number:3}. {column}"
        )

    print()

    print(
        f"Columns after standardization: "
        f"{len(df.columns)}"
    )

    print()

    return df

# ============================================================
# TRANSFORM - CLEAN STRING VALUES
# ============================================================

def clean_string_values(df):
    """
    Clean and normalize string-based columns.

    Different columns require different normalization rules.

    Examples:

        "  Lahore  " -> "Lahore"

        "LAHORE" -> "Lahore"

        "Energy" -> "energy"

        "BILAL@EXAMPLE.COM"
            -> "bilal@example.com"
    """

    print("=" * 70)
    print("TRANSFORM - CLEAN STRING VALUES")
    print("=" * 70)


    # ========================================================
    # 1. Company name
    # ========================================================

    if "company_name" in df.columns:

        df["company_name"] = (
            df["company_name"]
            .astype("string")
            .str.strip()
        )


    # ========================================================
    # 2. Company domain
    # ========================================================

    if "company_domain" in df.columns:

        df["company_domain"] = (
            df["company_domain"]
            .astype("string")
            .str.strip()
            .str.lower()
        )


    # ========================================================
    # 3. First name
    # ========================================================

    if "first_name" in df.columns:

        df["first_name"] = (
            df["first_name"]
            .astype("string")
            .str.strip()
            .str.title()
        )


    # ========================================================
    # 4. Last name
    # ========================================================

    if "last_name" in df.columns:

        df["last_name"] = (
            df["last_name"]
            .astype("string")
            .str.strip()
            .str.title()
        )


    # ========================================================
    # 5. Email
    # ========================================================

    if "email" in df.columns:

        df["email"] = (
            df["email"]
            .astype("string")
            .str.strip()
            .str.lower()
        )


    # ========================================================
    # 6. Generated email
    # ========================================================

    if "generated_email" in df.columns:

        df["generated_email"] = (
            df["generated_email"]
            .astype("string")
            .str.strip()
            .str.lower()
        )


    # ========================================================
    # 7. Customer name
    # ========================================================

    if "customer_name" in df.columns:

        df["customer_name"] = (
            df["customer_name"]
            .astype("string")
            .str.strip()
            .str.title()
        )


    # ========================================================
    # 8. City
    # ========================================================

    if "city" in df.columns:

        df["city"] = (
            df["city"]
            .astype("string")
            .str.strip()
            .str.title()
        )


    # ========================================================
    # 9. Country
    # ========================================================

    if "country" in df.columns:

        df["country"] = (
            df["country"]
            .astype("string")
            .str.strip()
            .str.title()
        )


    # ========================================================
    # 10. Industry
    # ========================================================
    #
    # Industry is a categorical field.
    #
    # We use lowercase so that:
    #
    # Energy
    # energy
    # ENERGY
    #
    # all become:
    #
    # energy
    #
    # ========================================================

    if "industry" in df.columns:

        df["industry"] = (
            df["industry"]
            .astype("string")
            .str.strip()
            .str.lower()
        )


    # ========================================================
    # 11. Deal name
    # ========================================================

    if "deal_name" in df.columns:

        df["deal_name"] = (
            df["deal_name"]
            .astype("string")
            .str.strip()
        )


    # ========================================================
    # 12. Product name
    # ========================================================

    if "product_name" in df.columns:

        df["product_name"] = (
            df["product_name"]
            .astype("string")
            .str.strip()
        )


    # ========================================================
    # 13. Status
    # ========================================================
    #
    # Status is another categorical field.
    #
    # Example:
    #
    # Won
    # WON
    # won
    #
    # become:
    #
    # won
    #
    # ========================================================

    if "status" in df.columns:

        df["status"] = (
            df["status"]
            .astype("string")
            .str.strip()
            .str.lower()
        )


    print(
        "String values cleaned successfully."
    )

    print()


    # ========================================================
    # Display some sample values
    # ========================================================

    print("Sample cleaned values:")

    columns_to_display = [
        "company_name",
        "industry",
        "first_name",
        "last_name",
        "email",
        "city",
        "country",
        "status"
    ]


    existing_columns = [
        column
        for column in columns_to_display
        if column in df.columns
    ]


    print(
        df[
            existing_columns
        ].head(10)
    )

    print()


    # ========================================================
    # Display unique industries
    # ========================================================

    if "industry" in df.columns:

        print(
            "Unique industry values after cleaning:"
        )

        print(
            df["industry"]
            .value_counts()
        )

        print()


    return df

# ============================================================
# TRANSFORM - CONVERT DATA TYPES
# ============================================================

def convert_data_types(df):
    """
    Convert important columns to their correct data types.

    Integer columns:
        company_id
        number_of_employees
        contact_id
        deal_id
        quantity

    Numeric columns:
        amount
        unit_price
        order_amount
        discount

    Boolean columns:
        is_active

    Date columns:
        close_date
        order_date
        created_date
        updated_date
    """

    print("=" * 70)
    print("TRANSFORM - CONVERT DATA TYPES")
    print("=" * 70)


    # ========================================================
    # INTEGER COLUMNS
    # ========================================================

    integer_columns = [
        "company_id",
        "number_of_employees",
        "contact_id",
        "deal_id",
        "quantity"
    ]


    for column in integer_columns:

        if column in df.columns:

            # ------------------------------------------------
            # Use pandas nullable integer type.
            #
            # "Int64" is different from normal "int64".
            #
            # Pandas "Int64" can represent:
            #
            #     10
            #     20
            #     <NA>
            #
            # This is useful when a column contains missing
            # values.
            # ------------------------------------------------

            df[column] = pd.to_numeric(
                df[column],
                errors="coerce"
            ).astype("Int64")


    # ========================================================
    # FLOAT / NUMERIC COLUMNS
    # ========================================================

    numeric_columns = [
        "amount",
        "unit_price",
        "order_amount",
        "discount"
    ]


    for column in numeric_columns:

        if column in df.columns:

            # ------------------------------------------------
            # Convert values to numeric.
            #
            # errors="coerce" means:
            #
            # If Pandas finds something that isn't a valid
            # number, it converts it to NaN instead of
            # crashing the entire pipeline.
            # ------------------------------------------------

            df[column] = pd.to_numeric(
                df[column],
                errors="coerce"
            )


    # ========================================================
    # BOOLEAN COLUMNS
    # ========================================================

    if "is_active" in df.columns:

        # Convert to Pandas nullable Boolean type.
        df["is_active"] = (
            df["is_active"]
            .astype("boolean")
        )


    # ========================================================
    # DATE COLUMNS
    # ========================================================

    date_columns = [
        "close_date",
        "order_date",
        "created_date",
        "updated_date"
    ]


    for column in date_columns:

        if column in df.columns:

            # ------------------------------------------------
            # Convert string/date values to Pandas datetime.
            #
            # Invalid dates become NaT.
            #
            # NaT means:
            #
            # "Not a Time"
            # ------------------------------------------------

            df[column] = pd.to_datetime(
                df[column],
                errors="coerce"
            )


    # ========================================================
    # DISPLAY RESULTING DATA TYPES
    # ========================================================

    print("Data types after conversion:")

    columns_to_display = [
        "company_id",
        "number_of_employees",
        "contact_id",
        "deal_id",
        "quantity",
        "amount",
        "unit_price",
        "order_amount",
        "discount",
        "is_active",
        "close_date",
        "order_date",
        "created_date",
        "updated_date"
    ]


    existing_columns = [
        column
        for column in columns_to_display
        if column in df.columns
    ]


    print(
        df[
            existing_columns
        ].dtypes
    )

    print()


    return df

# ============================================================
# TRANSFORM - VALIDATE INVALID RECORDS
# ============================================================

def validate_records(df):
    """
    Validate records using business rules.

    This step does NOT simply check data types.
    It checks whether the data makes business sense.

    Examples:

        number_of_employees >= 0
        quantity > 0
        unit_price >= 0
        amount >= 0
        order_amount >= 0
        discount between 0 and 100
    """

    print("=" * 70)
    print("TRANSFORM - VALIDATE INVALID RECORDS")
    print("=" * 70)

    # --------------------------------------------------------
    # Create a mask containing invalid records.
    #
    # A mask is simply True / False for every row.
    # --------------------------------------------------------

    invalid_mask = pd.Series(
        False,
        index=df.index
    )

    # --------------------------------------------------------
    # Rule 1:
    # Number of employees cannot be negative.
    # --------------------------------------------------------

    if "number_of_employees" in df.columns:

        invalid_employee_count = (
            df["number_of_employees"] < 0
        )

        print(
            "Invalid employee counts:",
            invalid_employee_count.sum()
        )

        invalid_mask = (
            invalid_mask |
            invalid_employee_count
        )

    # --------------------------------------------------------
    # Rule 2:
    # Quantity should be greater than zero.
    # --------------------------------------------------------

    if "quantity" in df.columns:

        invalid_quantity = (
            df["quantity"] <= 0
        )

        print(
            "Invalid quantities:",
            invalid_quantity.sum()
        )

        invalid_mask = (
            invalid_mask |
            invalid_quantity
        )

    # --------------------------------------------------------
    # Rule 3:
    # Unit price cannot be negative.
    # --------------------------------------------------------

    if "unit_price" in df.columns:

        invalid_unit_price = (
            df["unit_price"] < 0
        )

        print(
            "Invalid unit prices:",
            invalid_unit_price.sum()
        )

        invalid_mask = (
            invalid_mask |
            invalid_unit_price
        )

    # --------------------------------------------------------
    # Rule 4:
    # Amount cannot be negative.
    # --------------------------------------------------------

    if "amount" in df.columns:

        invalid_amount = (
            df["amount"] < 0
        )

        print(
            "Invalid amounts:",
            invalid_amount.sum()
        )

        invalid_mask = (
            invalid_mask |
            invalid_amount
        )

    # --------------------------------------------------------
    # Rule 5:
    # Order amount cannot be negative.
    #
    # Remember that order_amount was intentionally allowed
    # to remain NULL earlier.
    #
    # Therefore we only consider NEGATIVE values invalid.
    # --------------------------------------------------------

    if "order_amount" in df.columns:

        invalid_order_amount = (
            df["order_amount"] < 0
        )

        print(
            "Invalid order amounts:",
            invalid_order_amount.sum()
        )

        invalid_mask = (
            invalid_mask |
            invalid_order_amount
        )

    # --------------------------------------------------------
    # Rule 6:
    # Discount must be between 0 and 100.
    #
    # Example:
    #
    # 10  -> valid
    # 50  -> valid
    # 100 -> valid
    # -5  -> invalid
    # 150 -> invalid
    # --------------------------------------------------------

    if "discount" in df.columns:

        invalid_discount = (
            (df["discount"] < 0) |
            (df["discount"] > 100)
        )

        print(
            "Invalid discounts:",
            invalid_discount.sum()
        )

        invalid_mask = (
            invalid_mask |
            invalid_discount
        )

    # --------------------------------------------------------
    # Count all invalid records.
    # --------------------------------------------------------

    invalid_records = df[
        invalid_mask
    ].copy()

    print()
    print(
        "Total invalid records:",
        len(invalid_records)
    )

    # --------------------------------------------------------
    # Display invalid records.
    #
    # We only display a few important columns instead of all
    # 127 columns.
    # --------------------------------------------------------

    if len(invalid_records) > 0:

        print()
        print("Sample invalid records:")

        columns_to_display = [
            "company_id",
            "number_of_employees",
            "quantity",
            "amount",
            "unit_price",
            "order_amount",
            "discount"
        ]

        existing_columns = [
            column
            for column in columns_to_display
            if column in invalid_records.columns
        ]

        print(
            invalid_records[
                existing_columns
            ].head(10)
        )

    else:

        print(
            "No invalid records found."
        )

    print()

    # --------------------------------------------------------
    # IMPORTANT:
    #
    # We are NOT deleting invalid records yet.
    #
    # In a real ETL pipeline we might:
    #
    # 1. Fix the value
    # 2. Reject the record
    # 3. Send it to a quarantine table
    # 4. Send it to a data-quality/error file
    #
    # For this learning project, we'll return the dataframe
    # unchanged and handle the invalid records explicitly.
    # --------------------------------------------------------

    return df, invalid_records

# ============================================================
# LOAD - SAVE PROCESSED DATASET AS CSV
# ============================================================

def save_to_csv(df):
    """
    Save the processed DataFrame as a CSV file.
    """

    print("=" * 70)
    print("LOAD - SAVE PROCESSED DATASET AS CSV")
    print("=" * 70)

    # Create the output directory if it doesn't exist.
    OUTPUT_DIR.mkdir(
        parents=True,
        exist_ok=True
    )

    # Define the output CSV file.
    output_file = OUTPUT_DIR / "processed_dataset.csv"

    # Save the DataFrame.
    #
    # index=False is important.
    #
    # Without it, Pandas would add its DataFrame index
    # as an extra column in the CSV.
    df.to_csv(
        output_file,
        index=False
    )

    print(
        f"CSV file saved successfully:"
    )

    print(
        output_file
    )

    print(
        f"Rows saved    : {len(df):,}"
    )

    print(
        f"Columns saved : {len(df.columns):,}"
    )

    print()

    return output_file


# ============================================================
# LOAD - SAVE PROCESSED DATASET AS PARQUET
# ============================================================

def save_to_parquet(df):
    """
    Save the processed DataFrame as a Parquet file.

    Parquet is a columnar file format commonly used in
    Data Engineering and analytics workloads.
    """

    print("=" * 70)
    print("LOAD - SAVE PROCESSED DATASET AS PARQUET")
    print("=" * 70)

    # Create the output directory if it doesn't exist.
    OUTPUT_DIR.mkdir(
        parents=True,
        exist_ok=True
    )

    # Define the output Parquet file.
    output_file = OUTPUT_DIR / "processed_dataset.parquet"

    # Save the DataFrame as Parquet.
    #
    # pyarrow is used as the Parquet engine.
    df.to_parquet(
        output_file,
        engine="pyarrow",
        index=False
    )

    print(
        "Parquet file saved successfully:"
    )

    print(
        output_file
    )

    print(
        f"Rows saved    : {len(df):,}"
    )

    print(
        f"Columns saved : {len(df.columns):,}"
    )

    print()

    return output_file

# ============================================================
# MAIN
# ============================================================

def main():

    print("=" * 70)
    print("STARTING PANDAS ETL")
    print("=" * 70)

    # --------------------------------------------------------
    # EXTRACT
    # --------------------------------------------------------

    df, loading_time = extract_data()


    # --------------------------------------------------------
    # INSPECT
    # --------------------------------------------------------

    inspect_dataset(
        df
    )


    # --------------------------------------------------------
    # TRANSFORM
    # --------------------------------------------------------

    df = remove_duplicates(
        df
    )

    df = handle_missing_values(
        df
    )

    df = standardize_column_names(
        df
    )

    df = clean_string_values(
        df
    )

    df = convert_data_types(
        df
    )

    df, invalid_records = validate_records(
        df
    )

    # --------------------------------------------------------
    # LOAD
    # --------------------------------------------------------

    save_to_csv(
        df
    )

    save_to_parquet(
        df
    )

    
    # --------------------------------------------------------
    # Final summary
    # --------------------------------------------------------

    print("=" * 70)
    print("PANDAS ETL COMPLETED")
    print("=" * 70)

    print()

# ============================================================
# PROGRAM ENTRY POINT
# ============================================================

if __name__ == "__main__":

    main()